### ISSUE TITLE
AttributeError: 'MultiDiGraph' object has no attribute 'node'

### ISSUE THREAD

**Issue by lingfish** [trstruth/rehearsal#11]
Hi,

I shoehorned your stuff into an LXC container, and all is well, except on random different workflows, I get the subject error.

An example: https://github.com/StackStorm/st2/blob/master/contrib/examples/actions/workflows/orquesta-join.yaml

It seems, but not 100% sure, that when more than one task "do"'s to the same later task, I get this.

Thoughts?

**Comment by trstruth** [comment]
hey, sorry I never saw the notification for this issue.  Seems I can't repro though:
![image](https://user-images.githubusercontent.com/9982381/120386093-0e651a80-c2dd-11eb-8c56-49a4811fd476.png)
is it still an issue for you?
