### ISSUE TITLE
Site/service is down?

### ISSUE THREAD

**Issue by kinow** [trstruth/rehearsal#23]
Hi,

I am reading the St2 Orquesta docs, and found the link to https://www.orquestaedit.com/ to visualize workflows, but it's failing to resolve for me? Any idea if it's a temporary glitch?

https://downforeveryoneorjustme.com/orquestaedit.com

![image](https://user-images.githubusercontent.com/304786/135566980-052cf7fd-cbd9-4874-94d0-291e1dfab1fa.png)

**Comment by trstruth** [comment]
hello, I wrote [rehearsal](github.com/trstruth/rehearsal) while I was working at Microsoft, and the orquestaedit site was running on employee azure credits.  I recently moved to a new role and Microsoft must’ve deleted my azure resources.

I think your alternatives are either to
* run the web server yourself (instructions in the readme of the repo)
* use the stackstorm web UI workflow editor tool (which I believe was open sourced relatively recently)

if the demand for having a site like orquestaedit is high enough, Id be open to paying for it to be hosted on my own dime, the st2 maintainers welcomed me into their community, helped me debug st2 issues and helped me grow as an engineer.

**Comment by kinow** [comment]
Hi @trstruth 

Thanks for writing rehearsal! I am willing to run it locally myself. Would it be OK to leave it open for a while? So others will be aware of the issue in the St docs.

I will try to prepare a PR to fix the link there, changing it to this repo instead. What do you think?

Bruno

**Comment by kinow** [comment]
BTW, just managed to get it working with no issues :+1: great job!
![Screenshot_2021-10-01_21-51-52](https://user-images.githubusercontent.com/304786/135594127-c2c5efb2-95b3-47e9-9c78-466c3967728e.png)
